version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  phoenix:
    build: ./phoenix_api
    environment:
      DATABASE_URL: ecto://postgres:postgres@db/phoenix_api
    command:
      - bash
      - -c
      - |
        if [ ! -f .migrated ]; then
          mix ecto.create;
          mix ecto.migrate;
          touch .migrated;
        fi;
        mix phx.server
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "4000:4000"

  symfony:
    build:
      context: ./symfony_app
      dockerfile: Dockerfile-dev
    userns_mode: "keep-id"
    volumes:
      - ./symfony_app:/var/www/html:Z
    ports:
      - "8000:8080"
